name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: Magic0323
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake-dark.gif?palette=github-dark
      - run: |
          sudo apt-get install -y gifsicle
          gifsicle -i dist/github-contribution-grid-snake.gif --delay 15 -o dist/github-contribution-grid-snake.gif
          gifsicle -i dist/github-contribution-grid-snake-dark.gif --delay 15 -o dist/github-contribution-grid-snake-dark.gif
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output